from . import res_company
from . import delivery_carrier
from . import fedex_package_details
from . import stock_package_type
from . import sale_order
from . import stock_picking_vts
from . import stamp_shipping_charge
from . import gls_location
from . import ups_location
